### ISSUE TITLE
No syntax highligting for Webassembly .wat files

### ISSUE THREAD

**Issue by jhaand** [rhysd/vim-wasm#5]
Hi,

Vim and Neovim do not format and hightlight `.wat` Webassebly Text files at this moment. I first submitted this issue on the Neovim repository, but for syntax issues they still refer to Vim. Then I looked at the CONTRIBUTING.md from Vim, I now think this is the correct repository to address this issue.  (see: https://github.com/neovim/neovim/issues/26005 ) 

### Problem

Webassembly text files now use the `.wat` file extension. The current stable release of Vim does not show syntax highlighting for this file extension. It does show syntax highlighting for the old `.wast` file extension. 

Tested on Neovim stable 0.9.4 and Vim 9.01894.

Workaround: 
Copy or link the `runtime/syntax/wast.nvim` to .runtime/syntax/wat.vim`.
Or rename the `.wat` file to the old `.wast` extension.

References:
https://webassembly.github.io/spec/core/text/conventions.html
https://webassembly.js.org/docs/contrib-wat-vs-wast.html

### Steps to reproduce

Create a Webassembly with `.wat` extension. Or download it from: https://github.com/eliben/wasm-wat-samples
```
cd wasm-wat-samples/add
vi add.wat # no syntax highligting
cp add.wat add.wast 
vi add.wast  # does syntax highlighting
```

### Expected behavior

Edit a Webassembly file with syntax highlighting that has a `.wat` extension. 

### Proposed solution
Use a `wat.vim` for syntax highlighting and other runtime files. I think this should be addressed in the same way as `.phtml` and `.php` files use the same syntax highlighting and other runtime files. Thus by doing all the runtime things in the `wat.vim` file and make the `wast.vim` files import the corresponding settings. 

### Neovim version (nvim -v)

NVIM v0.9.4

### Vim (not Nvim) behaves the same?

yes, 9.0.1894

### Operating system/version

Debian GNU/Linux trixie/sid x86_64 

### Terminal name/version

Konsole 23.08.1

### $TERM environment variable

xterm-256color

### Installation

Flatpak

**Comment by rhysd** [comment]
Thank you for reaching out. This should be fixed in upstream. I'll make a patch.

**Comment by rhysd** [comment]
I sent [a patch](https://github.com/vim/vim/pull/13533) to Vim. You still need to wait for the patch being imported to Neovim.

Meanwhile, if you want, please set the following config (if you use init.lua, please translate it to Lua).

```vim
autocmd BufNewFile,BufReadPost *.wat setlocal filetype=wast
```

Or install `rhysd/vim-wasm` as plugin.

**Comment by jhaand** [comment]
Thank you for taking care of this so swiftly. 
I think this also implements everything quite neat.

I will try to convert the config line to lua shortly.

**Comment by jhaand** [comment]
Tested and verified via Lazy package manager on Neovim 0.9.4. 

Closing issue.

**Comment by jhaand** [comment]
The lua equivalent. Took some figuring out, but at least I learned something. 

```
vim.api.nvim_create_autocmd(
    {
        "BufNewFile",
        "BufRead",
    },
    {
        pattern = "*.wat",
        callback = function()
            local buf = vim.api.nvim_get_current_buf()
            vim.api.nvim_buf_set_option(buf, "filetype", "wast")
        end
    }
)
```
But I prefer to use the package manager to keep it clean.

**Comment by rhysd** [comment]
The patch was merged to both Vim and Neovim.　

- From next version of Neovim (0.9.5?)
- Vim 9.0.2104 or later

`wast` filetype will be replaced with `wat` filetype. The `wat` filetype will be applied to both `.wat` and `.wast` files.
